### ISSUE TITLE
Code Execution

### ISSUE THREAD

**Issue by Hickles02** [Hickles02/FYP478#7]
https://github.com/Hickles02/FYP478/blob/77396aace18d3152b7a4fe47f8b567958ceb13d6/MATLAB/simulate_ODEs.m#L26-L37

@tmlouw 
This part of the code slows the execution down considerably. I've doubled checked that the calculations are coded correctly, so do you have any idea why it might be taking so long to run? 
Thanks.

**Comment by tmlouw** [comment]
I ran the profiler on MATLAB ("Run and time"). The code is being identified as a problem not because it takes long to execute, but because it is being executed so many times. The reason for the high number of function calls is because the numerical integrator is taking very small step sizes. The numerical integrator is taking very small step sizes because you haven't specified a parameter that relates the liquid flowrate to the molar hold-up: you still have 'v.L(:,n) = sqrt(MM(n))'. This results in very high flowrates, which results in very large derivative values, which results in very small steps being taken. If I change this to `v.L(:,n) = 1e-3*sqrt(MM(n))`, the code runs in a matter of seconds.

**Comment by Hickles02** [comment]
Awesome. Thanks Professor.
